### PR TITLE
Few tweaks

### PR DESCRIPTION
**Pull request by rshura**
* Write dynamics before the note: this seems to look correct in Finale.
* Minor simplification.
* More white-space nit-picks.

### CODE REVIEW

**Comment by rshura** [comment]
I remember @jpvoigt saying that dynamics we're one moment late in MuseScore, so I think it should be easy for him to check.

**Comment by jpvoigt** [comment]
OK I haven't had the chance to deeply look into this, but it looks harmless ;-) so merged it to test it

**Comment by jpvoigt** [comment]
OK I test with the 3 example-files.
Now the dynamics are in place.
In example2 the Hairpin seems to be a little problem: MuseScore says
something about "wedge" not in the right position and it doesn't end at
the piano, but that is not a static Dynamic event, so it is another
issue ;-)

Am 07.11.18 um 18:28 schrieb Alex Roitman:

**Comment by rshura** [comment]
Hmm, I moved both absolute- and span- dynamics in front of the note, since
they both seemed late before.  Now they look correct in Finale.

Now that I look at example 2, I guess one thing I didn't do, and that has
nothing to do with "before-or-after-the-note" question, is the failure to
terminate hairpins on absolute dynamic event.  In example 2, there's
crescendo follow by a \f rather than \!  Since I'm parsing events in this
case, I think I never get the end event.

I'll check this tonight, maybe even fix it if my guess is correct.  I my
guess is correct, you should see the same hairpin issue with example2 even
without my latest change :-)

Thanks,
Alex

**Comment by jpvoigt** [comment]
That sounds reasonable. I guess you are right.

Am 07.11.18 um 18:49 schrieb Alex Roitman:
> Hmm, I moved both absolute- and span- dynamics in front of the note, since
> they both seemed late before. Now they look correct in Finale.
> 
> Now that I look at example 2, I guess one thing I didn't do, and that has
> nothing to do with "before-or-after-the-note" question, is the failure to
> terminate hairpins on absolute dynamic event. In example 2, there's
> crescendo follow by a \f rather than \! Since I'm parsing events in this
> case, I think I never get the end event.
> 
> I'll check this tonight, maybe even fix it if my guess is correct. I my
> guess is correct, you should see the same hairpin issue with example2 even
> without my latest change :-)
> 
> Thanks,
> Alex
>

**Pull request merged**
